config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :experiments, only: [:index, :show]
  
  root 'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  default_scope -> { order('created_at DESC') }

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  USERS = { "gb" => "123456" }
 
  before_action :authenticate
 
  private
 
  def authenticate
    authenticate_or_request_with_http_digest do |username|
      USERS[username]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @post.comments << @comment
    redirect_to experiment_path(@post)
  end

  def destory
    
  end

  private

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def index
    @exps = Post.all
  end

  def show
    @exp = Post.find(params[:id])
    @comments = @exp.comments.paginate(page: params[:page], per_page: 5)
  end
end

app/controllers/posts_controller.rb
class PostsController < AdminsController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :content, :cover_url, :background_url, :swf_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<div>
  <span>Commented <%= time_ago_in_words(comment.created_at) %> ago</span>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@exp, @exp.comments.build]) do |f| %>
  <div>
    <p>
      <%= f.text_area :commenter, rows:"1"%>
    </p>
    <p>
      <%= f.text_area :body, rows:"3"%>
    </p>
    <p>
      <%= f.submit %>
    </p>
  </div>
<% end %>

app/views/experiments/index.html.erb
<h1>All Experiments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Cover url</th>
      <th>Background url</th>
      <th>Swf url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @exps.each do |exp| %>
      <tr>
        <td><%= exp.title %></td>
        <td><%= exp.content %></td>
        <td><%= exp.cover_url %></td>
        <td><%= exp.background_url %></td>
        <td><%= exp.swf_url %></td>
        <td><%= link_to 'Show', experiment_path(exp) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Title: <%= @exp.title %></h1>

<p>
  <strong>Content:</strong>
  <%= @exp.content %>
</p>

<p>
  <strong>Cover url:</strong>
  <%= @exp.cover_url %>
</p>

<p>
  <strong>Background url:</strong>
  <%= @exp.background_url %>
</p>

<p>
  <strong>Swf url:</strong>
  <%= @exp.swf_url %>
</p>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<h2>Comments:</h2>
<%= render @comments %>

<%= will_paginate @comments %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">footer</a>
    is here.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="">
  <div class="">
    <%= link_to "NNN", root_path, id: "logo" %>
    <nav>
      <ul class="">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Exp", experiments_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NNN</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :cover_url %><br>
    <%= f.text_field :cover_url %>
  </div>
  <div class="field">
    <%= f.label :background_url %><br>
    <%= f.text_field :background_url %>
  </div>
  <div class="field">
    <%= f.label :swf_url %><br>
    <%= f.text_field :swf_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Cover url</th>
      <th>Background url</th>
      <th>Swf url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.cover_url %></td>
        <td><%= post.background_url %></td>
        <td><%= post.swf_url %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Cover url:</strong>
  <%= @post.cover_url %>
</p>

<p>
  <strong>Background url:</strong>
  <%= @post.background_url %>
</p>

<p>
  <strong>Swf url:</strong>
  <%= @post.swf_url %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/about.html.erb
<h1>ABOUT PAGE</h1>

app/views/static_pages/home.html.erb
<h1>HOME PAGE</h1>